apiVersion: apps/v1
kind: Deployment
metadata:
  name: goweb
  labels:
    app: goweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goweb
  template:
    metadata:
      labels:
        app: goweb
    spec:
      containers:
      - name: goweb
        image: registry.cn-hangzhou.aliyuncs.com/k6s/goweb:0.0.2
        env:
        - name: MY_NAME
          value: zhangsan
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: goweb
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.56.101
  selector:
    app: goweb
  ports:
    - port: 8000
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: goweb8001
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.56.101
  selector:
    app: goweb
  ports:
    - port: 8001
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: goweb-dhcp
spec:
  type: LoadBalancer
  loadBalancerIP: 0.0.0.0
  selector:
    app: goweb
  ports:
    - port: 8002
      targetPort: 80